routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
})->name('login');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cafe', 'HomeController@cafe')->name('cafe');


Route::resource('/userman','UserController');
Route::post('/userman/search','UserController@search')->name('userman.search');

Route::get('/myprofile','MyProfileController@index')->name('myprofile');
Route::get('/myprofile/edit','MyProfileController@edit')->name('myprofile.edit');
Route::patch('/myprofile/update','MyProfileController@update')->name('myprofile.update');

Route::get('/tes/myht', 'TreavelExpenseController@myht')->name('tes.myht');
Route::get('/tes/mydc', 'TreavelExpenseController@mydc')->name('tes.mydc');
Route::get('/tes/myht/create', 'TreavelExpenseController@create')->name('tes.myht.create');
Route::get('/tes/mydc/create', 'TreavelExpenseController@create')->name('tes.mydc.create');
//Route::post('/tes/store', 'TreavelExpenseController@store')->name('tes.store');
//Route::delete('/tes/destroy', 'TreavelExpenseController@destroy')->name('tes.destroy');
Route::get('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreate')->name('tes.mydc.create.mycarcreatecurrent');
Route::post('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreateCust')->name('tes.mydc.create.mycarcreatecustom');
Route::post('/tes/mydc/create/car/store', 'TreavelExpenseController@carexpstore')->name('tes.mydc.carexpstore');


Route::get('/tes/admin','AdminTravelExpenseController@index')->name('admin.tes.index');
Route::post('/tes/admin/filter','AdminTravelExpenseController@filter')->name('admin.tes.filter');
Route::post('/tes/admin/filter/docview/', 'AdminTravelExpenseController@showdoc')->name('admin.tes.displayDoc');

Route::resource('/tes','TreavelExpenseController') ;
Route::resource('/cutoffdates','CutoffDatesController');

//cafe routes
Route::resource('/cafe/suppliers','CafeSupplierController') ;
Route::resource('/cafe/families','CafeFamilyController') ;
Route::resource('/cafe/elements','CafeElementController') ;
Route::resource('/cafe/plan','CafePlanController') ;

resources/views/cafe.blade.php
@extends('layouts.homeLayout')

@section('content')

  <h1>Cafeeeee</h1>

@endsection

resources/views/editmyprofile.blade.php
@extends('layouts.homeLayout')
@section('content')

<div class="container mc-auto bg-white shadow-sm">

    <h1>Edit My Profile</h1>


  <div class="container mc-auto bg-white shadow-sm">
    @include('layouts.errordiv')
    <form  id="savemyprofile" action="{{ route('myprofile.update') }}" method="post">
        {{ method_field('PATCH') }}

      @csrf
    <table class="table .table-striped .table-hover" style="width:100%">
      <tr>
        <td>{{ __('Company ID')}}</td>
        <td> {{ $user->username }} </td>
      </tr>
      <tr>
        <td>{{ __('Full Name')}}</td>
        <td>{{ decrypt($user->fullname) }} </td>
      </tr>
      <tr>
        <td>{{ __('E-mail')}}</td>
        <td>{{ $user->email }} </td>
      </tr>
      <tr>
        <td>{{ __('Joining Date')}}</td>
        <td>{{ decrypt($user->joining_date) }}</td>
      </tr>
      <tr>
        <td>{{ __('Termination Date')}}</td>
        <td> {{ ($user->termination_date !== null ) ? decrypt($user->termination_date) : 'N/A'}} </td>
      </tr>
      <tr>
        <td>{{ __('Tax ID')}}</td>
        <td><input type="text" name="taxId" value="{{ isset($user) ? decrypt($user->tax_id) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('Permanent address')}}</td>
        <?php
          if(isset($user) && $user->perm_address !== null){
            $perm = explode('__' , decrypt($user->perm_address));
          }
        ?>
        <td>
          <input type="text" name="permAddressCtry" required placeholder="Country" value="{{ isset($perm[0]) ? $perm[0] : ''}}"/>
          <input type="text" name="permAddressZip" required placeholder="Zip Code" value="{{ isset($perm[1]) ? $perm[1] : ''}}"/>
          <input type="text" name="permAddressCity" required placeholder="City" value="{{ isset($perm[2]) ? $perm[2] : ''}}"/>
          <input type="text" name="permAddressStreet" required placeholder="Street" value="{{ isset($perm[3]) ? $perm[3] : ''}}"/>
          <input type="text" name="permAddressNum" required placeholder="Number" value="{{ isset($perm[4]) ? $perm[4] : ''}}"/>
          <input type="text" name="permAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($perm[5]) ? $perm[5] : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Temporary Address')}}</td>
        <?php
          if(isset($user) && $user->temp_address !== null){
            $temp = explode('__' , decrypt($user->temp_address));
          }
        ?>
        <td>
          <input type="text" name="tempAddressCtry"  placeholder="Country" value="{{ isset($temp[0]) ? $temp[0] : ''}}"/>
          <input type="text" name="tempAddressZip"  placeholder="Zip Code" value="{{ isset($temp[1]) ? $temp[1] : ''}}"/>
          <input type="text" name="tempAddressCity"  placeholder="City" value="{{ isset($temp[2]) ? $temp[2] : ''}}"/>
          <input type="text" name="tempAddressStreet"  placeholder="Street" value="{{ isset($temp[3]) ? $temp[3] : ''}}"/>
          <input type="text" name="tempAddressNum"  placeholder="Number" value="{{ isset($temp[4]) ? $temp[4] : ''}}"/>
          <input type="text" name="tempAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($temp[5]) ? $temp[5] : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Unofficial Temporary Address')}}</td>
        <?php
          if(isset($user) && $user->temp_unoff_address !== null){
            $tempUO = explode('__' , decrypt($user->temp_unoff_address));
          }
        ?>
        <td>
          <input type="text" name="tempUOAddressCtry"  placeholder="Country" value="{{ isset($tempUO[0]) ? $tempUO[0] : ''}}"/>
          <input type="text" name="tempUOAddressZip"  placeholder="Zip Code" value="{{ isset($tempUO[1]) ? $tempUO[1] : ''}}"/>
          <input type="text" name="tempUOAddressCity"  placeholder="City" value="{{ isset($tempUO[2]) ? $tempUO[2] : ''}}"/>
          <input type="text" name="tempUOAddressStreet"  placeholder="Street" value="{{ isset($tempUO[3]) ? $tempUO[3] : ''}}"/>
          <input type="text" name="tempUOAddressNum"  placeholder="Number" value="{{ isset($tempUO[4]) ? $tempUO[4] : ''}}"/>
          <input type="text" name="tempUOAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($tempUO[5]) ? $tempUO[5] : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Commuting Daily from')}}</td>
        <td>
            <select class="" name="selectCommuteFrom">
              <option value="perm" {{ $user->daily_commute_from == 'perm' ? 'selected' : ''}} >
                {{ __('Permanent Address')}}
              </option>
              <option value="temp" {{ $user->daily_commute_from == 'temp' ? 'selected' : ''}}>
                {{ __('Temporary Address')}}
              </option>
              <option value="tempUO" {{ $user->daily_commute_from == 'tempUO' ? 'selected' : ''}}>
                {{ __('Temporary Address (unofficcial)')}}
              </option>
            </select>
        </td>
      </tr>

      <tr>
        <td>{{ __('Car Commute Allowed')}}</td>
        <td>{{ $user->car_allowed == 1 ? 'Yes' : 'No' }}</td>
      </tr>
      @if($user->car_allowed == 1)
      <tr>
        <td>{{ __('Car Allowance')}}</td>
        <td>{{ $user->car_allowance_limit >= 1 ? $user->car_allowance_limit : 'Not limited' }}</td>
      </tr>
      @endif
      <tr>
        <td>{{ __('License Plate')}}</td>
        <td><input type="text" name="licensePlate" value="{{ $user->licence_plate != null ? decrypt($user->licence_plate) : '' }}" /></td>
      </tr>
      <tr>
        <td>{{ __('Preferred Language')}}</td>
        <td><select class="" name="selectPreferredLang">
              <option value="en" {{ isset($user) && $user->preferred_lang == 'en' ? 'selected' : ''}}>English</option>
              <option value="hu" {{ isset($user) && $user->preferred_lang == 'hu' ? 'selected' : ''}}>Magyar</option>
            </select>
        </td>
      </tr>
    </table>
    <button class="btn btn-primary" type="submit" name="button">Save</button>
  </form>

  </div>

</div>

@endsection

resources/views/home.blade.php
@extends('layouts.homeLayout')
@section('content')
<h1>welcome</h1>

@endsection

resources/views/login.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">{{ __('Login to Horus Solution Portal') }}</div>

                  <div class="card-body">
                      <form method="POST" action="{{ route('login') }}">
                          @csrf

                          <div class="form-group row">
                              <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                              <div class="col-md-6">
                                  <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                  @error('email')
                                      <span class="invalid-feedback" role="alert">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                  @enderror
                              </div>
                          </div>

                          <div class="form-group row">
                              <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                              <div class="col-md-6">
                                  <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                  @error('password')
                                      <span class="invalid-feedback" role="alert">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                  @enderror
                              </div>
                          </div>

                          <div class="form-group row">
                              <div class="col-md-6 offset-md-4">
                                  <div class="form-check">
                                      <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                      <label class="form-check-label" for="remember">
                                          {{ __('Remember Me') }}
                                      </label>
                                  </div>
                              </div>
                          </div>

                          <div class="form-group row mb-0">
                              <div class="col-md-8 offset-md-4">
                                  <button type="submit" class="btn btn-primary">
                                      {{ __('Login') }}
                                  </button>

                                  @if (Route::has('password.request'))
                                      <a class="btn btn-link" href="{{ route('password.request') }}">
                                          {{ __('Forgot Your Password?') }}
                                      </a>
                                  @endif
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</body>
</html>

resources/views/myprofile.blade.php
@extends('layouts.homeLayout')
@section('content')
  <div class="container mc-auto bg-white shadow-sm">
    <h1>My profile</h1>
  </div>

  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      <tr>
        <td>{{ __('Company ID')}}</td>
        <td>{{ $user->username }}</td>
      </tr>
      <tr>
        <td>{{ __('Full Name')}}</td>
        <td>{{ decrypt($user->fullname) }}</td>
      </tr>
      <tr>
        <td>{{ __('E-mail')}}</td>
        <td>{{ $user->email }}</td>
      </tr>
      <tr>
        <td>{{ __('Joining Date')}}</td>
        <td>{{ decrypt($user->joining_date) }}</td>
      </tr>

      <tr>
        <td>{{ __('Account status')}}</td>
        @if($user->user_status === 0)
          <td>Active, but personal data missing</td>
        @elseif($user->user_status === 1)
          <td>Active</td>
        @else
          <td>Disabled</td>
        @endif
      </tr>
      <tr>
        <td>{{ __('Tax ID')}}</td>
        <td>{{ decrypt($user->tax_id) }}</td>
      </tr>
      <tr>
        <td>{{ __('Permanent address')}}</td>
        <td>{{ isset($user->perm_address) ? str_replace('_',' ' , decrypt($user->perm_address)) : ''}}</td>
      </tr>
      <tr>
        <td>{{ __('Temporary Address')}}</td>
        <td>{{ isset($user->temp_address) ? str_replace('_',' ' ,decrypt($user->temp_address)) : '' }}</td>
      </tr>
      <tr>
        <td>{{ __('Unofficial Temporary Address')}}</td>
        <td>{{ isset($user->temp_unoff_address) ? str_replace('_',' ' ,decrypt($user->temp_unoff_address)) : '' }}</td>
      </tr>
      <tr>
        <td>{{ __('Commuting Daily from')}}</td>
        @if($user->daily_commute_from == 'perm')
          <td> {{ __('Permanent Address')}}</td>
        @elseif($user->daily_commute_from == 'temp')
          <td> {{ __('Temporary Address')}}</td>
        @else
          <td> {{ __('Temporary Unofficial Address')}}</td>
        @endif
      </tr>
      <tr>
        <td>{{ __('Commute Distance (km)')}}</td>
        <td>{{ isset($user->commute_distance)  ? $user->commute_distance : 'N/A'}}</td>
      </tr>
      <tr>
        <td>{{ __('Car Commute Allowed')}}</td>
        @if($user->car_allowed === 0 || $user->car_allowed === null)
          <td>No</td>
        @else
          <td>Yes</td>
        @endif
      </tr>
      <tr>
        <td>{{ __('Car Allowance')}}</td>
        <td>{{ $user->car_allowance_limit }}</td>
      </tr>
      <tr>
        <td>{{ __('License Plate')}}</td>
        <td>{{ decrypt($user->licence_plate) }}</td>
      </tr>
      <tr>
        <td>{{ __('Preferred Language')}}</td>
        <td>{{ $user->preferred_lang }}</td>
      </tr>
    </table>
    <a href="{{ route('myprofile.edit') }}"> <button class="btn btn-primary" type="button" name="button">Edit my profile</button> </a>
  </div>



@endsection

resources/views/newuser.blade.php
@extends('layouts.homeLayout')
@section('content')

<div class="container mc-auto bg-white shadow-sm">
  @if (isset($user))
    <h1>Edit User</h1>
  @else
  <h1>Add New User</h1>
  @endif
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    @if (!isset($user))
      <form  id="addNewUserForm" action="{{ route('userman.store') }}" method="post">
    @else
      <form  id="addNewUserForm" action="{{ route('userman.update', $user->id ) }}" method="post">
        {{ method_field('PATCH') }}
    @endif
      @csrf
    <table class="table .table-striped .table-hover" style="width:100%">
      <tr>
        <td>{{ __('Company ID')}}</td>
        <td> <input type="text" name="companyId" value="{{ isset($user) ? $user->username : ''}}" /> </td>
      </tr>
      <tr>
        <td>{{ __('Full Name')}}</td>
        <td><input type="text" name="fullName" value="{{ isset($user) ? decrypt($user->fullname) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('E-mail')}}</td>
        <td><input type="text" name="email" value="{{  isset($user) ? $user->email : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('Joining Date')}}</td>
        <td><input type="date" name="joiningDate" value="{{  isset($user) ? decrypt($user->joining_date) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('Termination Date')}}</td>
        <td><input type="date" name="terminationDate" value="{{ ( isset($user) && $user->termination_date !== null ) ? decrypt($user->termination_date) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('Role')}}</td>
        <td>
          <select class="" name="selectUserRole">
            <option value="user" {{ isset($user) && decrypt($user->roles) == 'user' ? 'selected' : ''}}>User</option>
            <option value="admin" {{ isset($user) && decrypt($user->roles) == 'admin' ? 'selected' : ''}}>Administrator</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>{{ __('Tax ID')}}</td>
        <td><input type="text" name="taxId" value="{{ isset($user->tax_id) ? decrypt($user->tax_id) : ''}}"/></td>
      </tr>

      <tr>
        <td>{{ __('Permanent address')}}</td>
        <?php
          if(isset($user) && $user->perm_address !== null){
            $perm = explode('__' , decrypt($user->perm_address));
          }
        ?>
        <td>
          <input type="text" name="permAddressCtry"  placeholder="Country" value="{{ isset($perm[0]) ? $perm[0] : ''}}"/>
          <input type="text" name="permAddressZip"  placeholder="Zip Code" value="{{ isset($perm[1]) ? $perm[1] : ''}}"/>
          <input type="text" name="permAddressCity"  placeholder="City" value="{{ isset($perm[2]) ? $perm[2] : ''}}"/>
          <input type="text" name="permAddressStreet"  placeholder="Street" value="{{ isset($perm[3]) ? $perm[3] : ''}}"/>
          <input type="text" name="permAddressNum"  placeholder="Number" value="{{ isset($perm[4]) ? $perm[4] : ''}}"/>
          <input type="text" name="permAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($perm[5]) ? $perm[5] : ''}}"/>
        </td>
      </tr>

      <tr>
        <td>{{ __('Temporary Address')}}</td>
        <?php
          if(isset($user) && $user->temp_address !== null){
            $temp = explode('__' , decrypt($user->temp_address));
          }
        ?>
        <td>
          <input type="text" name="tempAddressCtry"  placeholder="Country" value="{{ isset($temp[0]) ? $temp[0] : ''}}"/>
          <input type="text" name="tempAddressZip"  placeholder="Zip Code" value="{{ isset($temp[1]) ? $temp[1] : ''}}"/>
          <input type="text" name="tempAddressCity"  placeholder="City" value="{{ isset($temp[2]) ? $temp[2] : ''}}"/>
          <input type="text" name="tempAddressStreet"  placeholder="Street" value="{{ isset($temp[3]) ? $temp[3] : ''}}"/>
          <input type="text" name="tempAddressNum"  placeholder="Number" value="{{ isset($temp[4]) ? $temp[4] : ''}}"/>
          <input type="text" name="tempAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($temp[5]) ? $temp[5] : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Unofficcial Temporary Address')}}</td>
        <?php
          if(isset($user) && $user->temp_unoff_address !== null){
            $tempUO = explode('__' , decrypt($user->temp_unoff_address));
          }
        ?>
        <td>
          <input type="text" name="tempUOAddressCtry"  placeholder="Country" value="{{ isset($tempUO[0]) ? $tempUO[0] : ''}}"/>
          <input type="text" name="tempUOAddressZip"  placeholder="Zip Code" value="{{ isset($tempUO[1]) ? $tempUO[1] : ''}}"/>
          <input type="text" name="tempUOAddressCity"  placeholder="City" value="{{ isset($tempUO[2]) ? $tempUO[2] : ''}}"/>
          <input type="text" name="tempUOAddressStreet"  placeholder="Street" value="{{ isset($tempUO[3]) ? $tempUO[3] : ''}}"/>
          <input type="text" name="tempUOAddressNum"  placeholder="Number" value="{{ isset($tempUO[4]) ? $tempUO[4] : ''}}"/>
          <input type="text" name="tempUOAddressStairDoor" placeholder="Stairs and Door" value="{{ isset($tempUO[5]) ? $tempUO[5] : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Commuting Daily from')}}</td>
        <td>
          <select class="" name="selectCommuteFrom">
            <option value="perm" {{ isset($user) && $user->daily_commute_from == 'perm' ? 'selected' : ''}} >
              {{ __('Permanent Address')}}
            </option>
            <option value="temp" {{ isset($user) && $user->daily_commute_from == 'temp' ? 'selected' : ''}}>
              {{ __('Temporary Address')}}
            </option>
            <option value="tempUO" {{ isset($user) && $user->daily_commute_from == 'tempUO' ? 'selected' : ''}}>
              {{ __('Temporary Address (unofficcial)')}}
            </option>
          </select>
        </td>
      </tr>
      <tr>
        <td>{{ __('Commute Distance (km)')}}</td>
        <td>{{ isset($user->commute_distance)  ? $user->commute_distance : 'N/A'}}</td>
      </tr>
      <tr>
        <td>{{ __('Car Commute Allowed') }}</td>
        <td><input type="checkbox" name="carAllowed" value="1" {{ isset($user) && $user->car_allowed == 1 ? 'checked' : '' }} /></td>

      <tr>
        <td>{{ __('Car Allowance')}}</td>
        <td><input type="text" name="carAllowanceLimit" value="{{ isset($user) && $user->car_allowance_limit != null ? $user->car_allowance_limit : '' }}" /></td>
      </tr>
      <tr>
        <td>{{ __('License Plate')}}</td>
        <td><input type="text" name="licensePlate" value="{{ isset($user) && $user->licence_plate != null ? decrypt($user->licence_plate) : '' }}" /></td>
      </tr>

      <tr>
        <td>{{ __('Preferred Language')}}</td>
        <td><select class="" name="selectPreferredLang">
          <option value="en" {{ isset($user) && $user->preferred_lang == 'en' ? 'selected' : ''}}>English</option>
          <option value="hu" {{ isset($user) && $user->preferred_lang == 'hu' ? 'selected' : ''}}>Magyar</option>
        </select> </td>
      </tr>
      <tr>
        <td>{{ __('Employee type:')}}</td>
        <td>
          <select class="" name="selectEmployeeType">
            <option value="full_perm">Full time,Permanent</option>
            <option value="full_cont">Full time,Contractor</option>
            <option value="part_perm">Part time,Permanent</option>
            <option value="part_cont">Part time,Contractor</option>
            <option value="dual">Dual Education</option>
            <option value="student">Student</option>
          </select>
        </td>
      </tr>

      @if(isset($user))
      <tr>
        <td colspan="2">{{ __('Cafetera Related Data')}}</td>
      </tr>
      <tr>
        <td>{{ __('Eligible for Cafeteria from:')}}</td>
        <td><input type="date" name="cafeEligibleFrom" value="{{  isset($user->cafe_eligible_from) ? $user->cafe_eligible_from : '' }}"/></td>
      </tr>
      <tr>
        <td>{{ __('Eligible for Cafeteria until:')}}</td>
        <td>
          <input type="date" name="cafeEligibleUntil" value="{{  isset($user->cafe_eligible_until) ? $user->cafe_eligible_until : ''}}"/>
        </td>
      </tr>
      <tr>
        <td>{{ __('Cafeteria yearly limit (calculated):')}}</td>
        <td><input type="text" name="cafeEligibleLimit" value="{{  isset($user->cafe_yearly_limit) ? $user->cafe_yearly_limit : ''}}"/></td>
      </tr>

      <tr>
        <td>{{ __('OTP Szép Card - Dining pocket:')}}</td>
        <td><input type="text" name="cafeSzepDining" value="{{  isset($user->cafe_szep_dining_pocket) && $user->cafe_szep_dining_pocket != null ? decrypt($user->cafe_szep_dining_pocket) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('OTP Szép Card - Leisure pocket:')}}</td>
        <td><input type="text" name="cafeSzepLeisure" value="{{  isset($user->cafe_szep_leisure_pocket) && $user->cafe_szep_leisure_pocket != null  ? decrypt($user->cafe_szep_leisure_pocket) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('OTP Szép Card - Accomodation pocket:')}}</td>
        <td><input type="text" name="cafeSzepAccom" value="{{  isset($user->cafe_szep_accom_pocket) && $user->cafe_szep_accom_pocket != null  ? decrypt($user->cafe_szep_accom_pocket) : ''}}"/></td>
      </tr>
      <tr>
        <td>{{ __('User open for declaration:')}}</td>
        <td><input type="checkbox" name="cafeDeclOpen" value="1" {{ isset($user) && $user->cafe_planning_open == 1 ? 'checked' : '' }} /></td>
      </tr>
      @endif
    </table>
    <button class="btn btn-primary" type="submit" name="button" >Save</button> </a>
    <button class="btn btn-primary" type="button" onclick="window.location='{{ URL::previous() }}'" name="cancelManageElement">Cancel</button>
  </form>

  </div>

</div>

@endsection

resources/views/usermanagement.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <h1>User Management</h1>
</div>
<div class="filters container mc-auto bg-white shadow-sm">
  <form id="searchUserForm" class="" action="{{ route('userman.search') }}" method="post">
    @csrf
    <input type="text" name="searchUserField" placeholder="name,username,e-mail"/>
    <select class="" name="selectUserStatus">
      <option value="9" selected>All</option>
      <option value="0">Active, but personal data missing </option>
      <option value="1">Active</option>
      <option value="2">Disabled</option>
    </select>
    <button class="btn btn-primary" type="button" name="button" onclick="document.getElementById('searchUserForm').submit();">
      Search
    </button>
  </form>

</div>
<div class="list container mc-auto bg-white shadow-sm">
  <table  class="table .table-striped .table-hover" style="width:100%">
    @foreach ($users as $user)
    <tr>
      <td>{{ $user -> username }}</td>
      <td>{{ decrypt($user -> fullname ) }}</td>
      <td>{{ $user -> email }}</td>
      <td>
        <a href="/userman/{{ $user->id }}/edit">
          <button type="button" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-edit"></span> Edit
          </button>
        </a>
        <a href="/userman/{{ $user->id }}/edit">
          <button type="button" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-edit"></span> PW Reset
          </button>
        </a>
        <form style="display:inline;" action="{{ route('userman.destroy', $user->id ) }}" method="post">
          {{ method_field('DELETE') }}
          @csrf
          <button type="submit" class="btn btn-primary btn-sm" >
            <span class="glyphicon glyphicon-trash"></span> Delete
          </button>
        </form>

      </td>
    </tr>
    @endforeach
  </table>

</div>
{{ $users->links() }}

@endsection