routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
})->name('login');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cafe', 'HomeController@cafe')->name('cafe');


Route::resource('/userman','UserController');
Route::post('/userman/search','UserController@search')->name('userman.search');

Route::get('/myprofile','MyProfileController@index')->name('myprofile');
Route::get('/myprofile/edit','MyProfileController@edit')->name('myprofile.edit');
Route::patch('/myprofile/update','MyProfileController@update')->name('myprofile.update');

Route::get('/tes/myht', 'TreavelExpenseController@myht')->name('tes.myht');
Route::get('/tes/mydc', 'TreavelExpenseController@mydc')->name('tes.mydc');
Route::get('/tes/myht/create', 'TreavelExpenseController@create')->name('tes.myht.create');
Route::get('/tes/mydc/create', 'TreavelExpenseController@create')->name('tes.mydc.create');
//Route::post('/tes/store', 'TreavelExpenseController@store')->name('tes.store');
//Route::delete('/tes/destroy', 'TreavelExpenseController@destroy')->name('tes.destroy');
Route::get('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreate')->name('tes.mydc.create.mycarcreatecurrent');
Route::post('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreateCust')->name('tes.mydc.create.mycarcreatecustom');
Route::post('/tes/mydc/create/car/store', 'TreavelExpenseController@carexpstore')->name('tes.mydc.carexpstore');


Route::get('/tes/admin','AdminTravelExpenseController@index')->name('admin.tes.index');
Route::post('/tes/admin/filter','AdminTravelExpenseController@filter')->name('admin.tes.filter');
Route::post('/tes/admin/filter/docview/', 'AdminTravelExpenseController@showdoc')->name('admin.tes.displayDoc');

Route::resource('/tes','TreavelExpenseController') ;
Route::resource('/cutoffdates','CutoffDatesController');

//cafe routes
Route::resource('/cafe/suppliers','CafeSupplierController') ;
Route::resource('/cafe/families','CafeFamilyController') ;
Route::resource('/cafe/elements','CafeElementController') ;
Route::resource('/cafe/plan','CafePlanController') ;

resources/views/tes/createcarexp.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    <h1 class="mc-auto">Add New Daily Commute Expense Item</h1>
  </div>
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">

      <div class="forCar">
      <table class="table .table-striped .table-hover" style="width:100%">
        <tr>
          <td> {{ __('Payroll Period')}} </td>
          <td>

            <form class="" action="{{ route('tes.mydc.create.mycarcreatecustom') }}" method="post">
              @csrf
              <select class="" name="selectCarMonth" onchange="this.form.submit()">
                <option value="{{ date('Y-F', time()) }}" {{ $month == date('F', time() ) ? 'selected':'' }} >{{ date('Y M', time()) }}</option>
                <option value="{{ date('Y-F', strtotime('-1 months' )) }}" {{ $month == date('F', strtotime('-1 months' )) ? 'selected':'' }}>{{ date('Y M', strtotime('-1 months' )) }}</option>
                <option value="{{ date('Y-F', strtotime('-2 months' )) }}" {{ $month == date('F', strtotime('-2 months' )) ? 'selected':'' }}>{{ date('Y M', strtotime('-2 months' )) }}</option>
                <option value="{{ date('Y-F', strtotime('-3 months' )) }}" {{ $month == date('F', strtotime('-3 months' )) ? 'selected':'' }}>{{ date('Y M', strtotime('-3 months' )) }}</option>
                <option value="{{ date('Y-F', strtotime('-4 months' )) }}" {{ $month == date('F', strtotime('-4 months' )) ? 'selected':'' }}>{{ date('Y M', strtotime('-4 months' )) }}</option>
                <option value="{{ date('Y-F', strtotime('-5 months' )) }}" {{ $month == date('F', strtotime('-5 months' )) ? 'selected':'' }}>{{ date('Y M', strtotime('-5 months' )) }}</option>
              </select>
            </form>
          </td>
        </tr>
        <tr>
          <td>{{ __('Travel Type')}}</td>
          <td>
            <select id="selectTT_id" class="" name="selectTravelType" onchange="traveltypereroute()">
              <option value="public">{{ __('Public Transport')}}</option>
              <option value="car" selected>{{ __('Car')}}</option>
            </select>
          </td>
        </tr>
        <tr>
          <td colspan="2">{{ __('Calculated distance from office:')}}</td>
        </tr>
        <tr>
          <td colspan="2">{{ auth()->user()->commute_distance }} km</td>
        </tr>
        <form class="" action="{{ route('tes.mydc.carexpstore') }}" method="post" >
          @csrf
          <input type="hidden" name="expType" value="dc"/>
          <input type="hidden" name="selectTravelType" value="car"/>
          @if(isset($arco))
          <tr>
            <td colspan="2">
              <table cellspacing="3" class="carcalendar">
                <tr>
                  <th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th><th>Sun</th>
                </tr>
                @if(date('D',strtotime($arco[0])) == 'Tue')
                  <tr><td></td>
                @endif
                @if(date('D',strtotime($arco[0])) == 'Wed')
                  <tr><td colspan="2"></td>
                @endif
                @if(date('D',strtotime($arco[0])) == 'Thu')
                  <tr><td colspan="3"></td>
                @endif
                @if(date('D',strtotime($arco[0])) == 'Fri')
                  <tr><td colspan="4"></td>
                @endif
                @if(date('D',strtotime($arco[0])) == 'Sat')
                  <tr><td colspan="5"></td>
                @endif
                @if(date('D',strtotime($arco[0])) == 'Sun')
                  <tr><td colspan="6"></td>
                @endif

                @foreach ($arco as $key => $day)
                  @if(date('D',strtotime($day)) == 'Mon')
                  <tr>
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Tue')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Wed')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Thu')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Fri')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Sat')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>
                  @endif
                  @if(date('D',strtotime($day)) == 'Sun')
                    <td class="carDayCheckboxTD" >
                      <input class="carDayCheckbox hidden" type="checkbox" name="day_{{$day}}" value="1"></input>
                       {{ $day }}
                     </td>

                  @endif
                @endforeach
                @if(date('D',strtotime(end($arco))) == 'Mon')
                  <td colspan="6"></td></tr>
                @endif
                @if(date('D',strtotime(end($arco))) == 'Tue')
                  <td colspan="5"></td></tr>
                @endif
                @if(date('D',strtotime(end($arco))) == 'Wed')
                  <td colspan="4"></td></tr>
                @endif
                @if(date('D',strtotime(end($arco))) == 'Thu')
                  <td colspan="3"></td></tr>
                @endif
                @if(date('D',strtotime(end($arco))) == 'Fri')
                  <td colspan="2"></td></tr>
                @endif
                @if(date('D',strtotime(end($arco))) == 'Sat')
                  <td ></td></tr>
                @endif

              </table>
            </td>
          </tr>


          @endif



          </table>
          <button class="btn btn-primary" type="submit" name="button">Save</button>
          <button class="btn btn-primary" type="button" name="cancel">Cancel</button>

        </form>
      </div>

  </div>
</div>
@endsection

resources/views/tes/createexp.blade.php
@extends('layouts.homeLayout')
@section('content')

<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    @if($expType == 'ht')
      <h1 class="mc-auto">Add New Home Travel Expense Item</h1>
    @elseif($expType == 'dc')
      <h1 class="mc-auto">Add New Daily Commute Expense Item</h1>
    @else
      <h1 class="mc-auto">Error</h1>
    @endif

  </div>
  @include('layouts.errordiv')
  
  <div class="container mc-auto bg-white shadow-sm">
    <form class="" action="{{ route('tes.store') }}" method="post" enctype="multipart/form-data">
      @csrf
      <input type="hidden" name="expType" value="{{ $expType }}"/>
      <table class="table .table-striped .table-hover" style="width:100%">
        <tr>
          <td>{{ __('Travel Type')}}</td>
          <td>
            <select id="selectTT_id" class="" name="selectTravelType" onchange="traveltypereroute()">
              <option value="public" selected>{{ __('Public Transport')}}</option>
              @if($expType == 'dc')
                <option value="car">{{ __('Car')}}</option>
              @endif
            </select>
          </td>
        </tr>
        <div class="forPublic">
          <tr>
            <td>{{ __('Ticket Type')}}</td>
            <td>
              <select class="" name="selectTicketType">
                <option value="ticket" {{  old('selectTicketType') == 'ticket' ? 'selected':''}}>{{ __('Ticket')}}</option>
                @if($expType == 'ht')
                  <option value="planeticket" {{ old('selectTicketType') == 'planeticket' ? 'selected':''}}>{{ __('Plane Ticket')}}</option>
                @endif
                @if($expType == 'dc')
                  <option value="pass" {{ old('selectTicketType') == 'pass' ? 'selected':''}}>{{ __('Monthly pass')}}</option>
                @endif
              </select>
            </td>
          </tr>
          <tr>
            <td>{{ __('Date of Travel')}}</td>
            <td> <input type="date" name="dateOfTravel"  value="{{ old('dateOfTravel')}}"/> </td>
          </tr>
          <tr>
            <td>{{ __('From')}}</td>
            <td>
              <select class="" name="selectFrom">
                @if(auth()->user()->perm_address !== null)
                  <option value="perm" {{ old('selectFrom') == 'perm' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->perm_address)) }}</option>
                @endif
                @if(auth()->user()->temp_address !== null)
                  <option value="temp" {{ old('selectFrom') == 'temp' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->temp_address)) }}</option>
                @endif
                @if(auth()->user()->temp_unoff_address !== null)
                  <option value="tempUO" {{ old('selectFrom') == 'tempUO' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->temp_unoff_address)) }}</option>
                @endif
                @if($expType == 'dc')
                  <option value="office" {{ old('selectFrom') == 'office' ? 'selected':''}}>ABG Office</option>
                @endif
              </select>
            </td>
          </tr>
          <tr>
            <td>{{ __('To')}}</td>
            <td>
              <select class="" name="selectTo">
                @if(auth()->user()->perm_address !== null)
                  <option value="perm" {{ old('selectTo') == 'perm' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->perm_address)) }}</option>
                @endif
                @if(auth()->user()->temp_address !== null)
                  <option value="temp" {{ old('selectTo') == 'temp' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->temp_address)) }}</option>
                @endif
                @if(auth()->user()->temp_unoff_address !== null)
                  <option value="tempUO" {{ old('selectTo') == 'tempUO' ? 'selected':''}}>{{ str_replace('__' ,' ', decrypt(auth()->user()->temp_unoff_address)) }}</option>
                @endif
                @if($expType == 'dc')
                  <option value="office" {{ old('selectTo') == 'office' ? 'selected':''}}>ABG Office</option>
                @endif
              </select>
            </td>
          </tr>
          <tr>
            <td>{{ __('Gross Price')}}</td>
            <td> <input type="text" name="grossAmount" value="{{ old('grossAmount')}}"> </td>
          </tr>
          <tr>
            <td>{{ __('Calculated refound')}}</td>
            <td> <div id="calcRefound_cell"></div> </td>
          </tr>
          <tr>
            <td>{{ __('Documents of purchase')}}</td>
            <td>
              <div class="file-upload-wrapper">
                <input multiple="multiple" type="file" name="docs[]" required/>
              </div>
            </td>
          </tr>
        </div>


      </table>
        <button class="btn btn-primary" type="submit" name="button">Save</button>
        <button class="btn btn-primary" type="button" name="cancel">Cancel</button>
      </form>
    </div>

</div>

@endsection

resources/views/tes/cutoffdatemng.blade.php
@extends('layouts.homeLayout')
@section('content')

<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    <h1 class="mc-auto">Cutoff Date MAnagement</h1>
  </div>
    @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    <form class="" action="{{ route('cutoffdates.store' ) }}" method="post">
      @csrf
      <table class="table .table-striped .table-hover" style="width:100%">
        <tr>
          <td></td>
          <td>{{__('Start')}}</td>
          <td>{{__('End')}}</td>
          <td></td>
        </tr>
        <tr>
          <td>{{__('Add New period:')}}</td>
          <td> <input type="date" name="coStart" /> </td>
          <td> <input type="date" name="coEnd" /> </td>
          <td> <button class="btn btn-primary" type="submit" name="button">Add this!</button> </td>
        </tr>
      </table>
    </form>
  </div>
  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      <thead>
        <tr>
          <th>{{ __('Year') }}</th>
          <th>{{__('Month') }}</th>
          <th>{{__('Starts on') }}</th>
          <th>{{__('Ends on') }}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($cutoffDates as $date)
          <tr>
            <td>{{ $date-> year }}</td>
            <td>{{ $date-> month }}</td>
            <td>{{ $date-> start }}</td>
            <td>{{ $date-> end }}</td>
            <td>
              <form style="display:inline;" action="{{ route('cutoffdates.destroy', $date->id ) }}" method="post">
                {{ method_field('DELETE') }}
                @csrf
                <button type="submit" class="btn btn-primary btn-sm" >
                  <span class="glyphicon glyphicon-trash"></span> Delete
                </button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>


@endsection

resources/views/tes/myitems.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">

@if(Route::current()->getName() == 'tes.myht')
  <h1 class="mc-auto">{{__('My Home Travel Expenses')}}</h1>
@elseif(Route::current()->getName() == 'tes.mydc')
  <h1 class="mc-auto">{{__('My Daily Commute Expenses')}}</h1>
@else
  <h1 class="mc-auto">{{__('My Expenses')}}</h1>
@endif
</div>
  @include('layouts.errordiv')
<div class="container mc-auto bg-white shadow-sm">
  <h3 class="mc-auto">Current Payroll period (Open until {{ $codt[0]['end']}})</h3>
  <table class="expTable table .table-striped .table-hover" style="width:100%">
    <thead class="thead-dark">
      <tr>
        <th>{{__('Travel Type')}}</th>
        <th>{{__('Ticket Type')}}</th>
        <th>{{__('Submission Month')}}</th>
        <th>{{__('Travel Date')}}</th>
        <th>{{__('From')}}</th>
        <th>{{__('To')}}</th>
        <th>{{__('Gross Amount')}}</th>
        <th>{{__('Distance')}}</th>
        <th>{{__('Refund')}}</th>
        <th>{{__('Status')}}</th>
        <th>{{__('Actions')}}</th>
      </tr>
    </thead>
  <tbody>

      @foreach ($travelExpense as $exp)
      <tr>
          <td> {{ $exp->travel_type == 'public' ? __('Public Transport') : __('Car')}} </td>
          <td>
            @if($exp->ticket_type == 'ticket')
              {{__('Ticket')}}
            @elseif($exp->ticket_type == 'planeticket')
              {{__('Plane Ticket')}}
            @elseif($exp->ticket_type == 'pass')
                {{__('Monthly Pass')}}
            @else
              {{__('N/A')}}
            @endif
          </td>
          <td> {{ __($exp->sub_month) }} </td>
          <td> {{ $exp->travel_date }} </td>
          <td> {{ $userAddr[$exp->travel_from] }} </td>
          <td> {{ $userAddr[$exp->travel_to] }} </td>
          <td> {{ $exp->exp_gross_amount }}  </td>
          <td> {{ $exp->exp_distance }} </td>
          <td class="refund_cell"> {{ $exp->exp_refund }}  </td>
          @if($exp->exp_status == 0)
          <td> {{__('Pending')}} </td>
          @elseif($exp->exp_status == 2)
          <td> {{__('Approved')}} </td>
          @else
          <td> {{__('Rejected')}} </td>
          @endif
          <td>
            <form class="" action="{{ route('tes.destroy',$exp->id) }}" method="post">
              {{ method_field('DELETE') }}
              @csrf
              <button class="btn btn-primary" type="submit" name="delExp"><span class="glyphicon glyphicon-trash"></span></button>
            </form>
          </td>
      </tr>
      @endforeach

  </tbody>
  <tfoot class="tfoot-dark">
    <tr>
      <td colspan="4" >{{__('Summary:')}}</td>
      <td colspan="4"><span class="num_items_cell"></span>  {{__(' items')}}</td>
      <td colspan="3"><span class="sum_items_cell"></span> HUF</td>
    </tr>
  </tfoot>

  </table>
  @if(Route::current()->getName() == 'tes.myht')
    <a href="{{ route( 'tes.myht.create' ) }}"> <button class="btn btn-primary" type="button" name="button">Add New Item</button> </a>
  @elseif(Route::current()->getName() == 'tes.mydc')
    <a href="{{ route( 'tes.mydc.create' ) }}"> <button class="btn btn-primary" type="button" name="button">Add New Item</button> </a>
  @else
    <a href="{{ route( 'tes.myht.create' ) }}"> <button class="btn btn-primary" type="button" name="button">Add New Item</button> </a>
  @endif
  <hr>
  <h3 class="mc-auto">Last Payroll periods(Closed)</h3>
  <table class="expTable table .table-striped .table-hover" style="width:100%">
    <thead class="thead-dark">
      <tr  class="tableshrink">
        <th colspan="11" >{{ $codt[1]['year']}} {{ $codt[1]['month']}}</th>
      </tr>
      <tr class="headerlist hidden">
        <th>{{__('Travel Type')}}</th>
        <th>{{__('Ticket Type')}}</th>
        <th>{{__('Submission Month')}}</th>
        <th>{{__('Travel Date')}}</th>
        <th>{{__('From')}}</th>
        <th>{{__('To')}}</th>
        <th>{{__('Gross Amount')}}</th>
        <th>{{__('Distance')}}</th>
        <th>{{__('Refund')}}</th>
        <th>{{__('Status')}}</th>
        <th>{{__('Comment')}}</th>
      </tr>
    </thead>
  <tbody class="hidden">
      @if($travelExpenseOld -> isEmpty())
        <td colspan="11"> {{ __('Nothing to display...')}} </td>
      @else
        @foreach ($travelExpenseOld as $exp1)
        <tr>
          <td> {{ $exp1->travel_type == 'public' ? __('Public Transport') : __('Car')}} </td>
          <td>
            @if($exp1->ticket_type == 'ticket')
              {{__('Ticket')}}
            @elseif($exp1->ticket_type == 'planeticket')
              {{__('Plane Ticket')}}
            @elseif($exp1->ticket_type == 'pass')
                {{__('Monthly Pass')}}
            @else
              {{__('N/A')}}
            @endif
          </td>
          <td> {{ __($exp1->sub_month) }} </td>
          <td> {{ $exp1->travel_date }} </td>
          <td> {{ $userAddr[$exp1->travel_from] }} </td>
          <td> {{ $userAddr[$exp1->travel_to] }} </td>
          <td> {{ $exp1->exp_gross_amount }}  </td>
          <td> {{ $exp1->exp_distance }} </td>
          <td class="refund_cell"> {{ $exp1->exp_refund }}  </td>
          @if($exp1->exp_status == 0)
          <td> {{__('Pending')}} </td>
          @elseif($exp1->exp_status == 2)
          <td> {{__('Approved')}} </td>
          @else
          <td> {{__('Rejected')}} </td>
          @endif
          <td> {{ $exp1->comment }} </td>
        </tr>
        @endforeach
      @endif

  </tbody>
  <tfoot class="tfoot-dark">
    <tr>
      <td colspan="4" >{{__('Summary:')}}</td>
      <td colspan="4"><span class="num_items_cell"></span>  {{__(' items')}}</td>
      <td colspan="3"><span class="sum_items_cell"></span> HUF</td>
    </tr>
  </tfoot>
  </table>

  <table class="expTable table .table-striped .table-hover" style="width:100%">
    <thead class="thead-dark">
      <tr  class="tableshrink">
        <th colspan="11" >{{ $codt[2]['year']}} {{ $codt[2]['month']}}</th>
      </tr>
      <tr class="headerlist hidden">
        <th>{{__('Travel Type')}}</th>
        <th>{{__('Ticket Type')}}</th>
        <th>{{__('Submission Month')}}</th>
        <th>{{__('Travel Date')}}</th>
        <th>{{__('From')}}</th>
        <th>{{__('To')}}</th>
        <th>{{__('Gross Amount')}}</th>
        <th>{{__('Distance')}}</th>
        <th>{{__('Refund')}}</th>
        <th>{{__('Status')}}</th>
        <th>{{__('Comment')}}</th>
      </tr>
    </thead>
  <tbody class="hidden">

      @if($travelExpenseOldest -> isEmpty())
        <td colspan="11"> {{ __('Nothing to display...')}} </td>
      @else
        @foreach ($travelExpenseOldest as $exp2)
        <tr>
          <td> {{ $exp2->travel_type == 'public' ? __('Public Transport') : __('Car')}} </td>
          <td>
            @if($exp2->ticket_type == 'ticket')
              {{__('Ticket')}}
            @elseif($exp2->ticket_type == 'planeticket')
              {{__('Plane Ticket')}}
            @elseif($exp2->ticket_type == 'pass')
                {{__('Monthly Pass')}}
            @else
              {{__('N/A')}}
            @endif
          </td>
          <td> {{ __($exp2->sub_month) }} </td>
          <td> {{ $exp2->travel_date }} </td>
          <td> {{ $userAddr[$exp2->travel_from] }} </td>
          <td> {{ $userAddr[$exp2->travel_to] }} </td>
          <td> {{ $exp2->exp_gross_amount }}  </td>
          <td> {{ $exp2->exp_distance }} </td>
          <td class="refund_cell"> {{ $exp2->exp_refund }}  </td>
          @if($exp2->exp_status == 0)
          <td> {{__('Pending')}} </td>
          @elseif($exp2->exp_status == 2)
          <td> {{__('Approved')}} </td>
          @else
          <td> {{__('Rejected')}} </td>
          @endif
          <td> {{ $exp2->comment }} </td>
        </tr>
        @endforeach
      @endif
  </tbody>
  <tfoot class="tfoot-dark">
    <tr>
      <td colspan="4" >{{__('Summary:')}}</td>
      <td colspan="4"><span class="num_items_cell"></span>  {{__(' items')}}</td>
      <td colspan="3"><span class="sum_items_cell"></span> HUF</td>
    </tr>
  </tfoot>
  </table>

</div>
@endsection