routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
})->name('login');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cafe', 'HomeController@cafe')->name('cafe');


Route::resource('/userman','UserController');
Route::post('/userman/search','UserController@search')->name('userman.search');

Route::get('/myprofile','MyProfileController@index')->name('myprofile');
Route::get('/myprofile/edit','MyProfileController@edit')->name('myprofile.edit');
Route::patch('/myprofile/update','MyProfileController@update')->name('myprofile.update');

Route::get('/tes/myht', 'TreavelExpenseController@myht')->name('tes.myht');
Route::get('/tes/mydc', 'TreavelExpenseController@mydc')->name('tes.mydc');
Route::get('/tes/myht/create', 'TreavelExpenseController@create')->name('tes.myht.create');
Route::get('/tes/mydc/create', 'TreavelExpenseController@create')->name('tes.mydc.create');
//Route::post('/tes/store', 'TreavelExpenseController@store')->name('tes.store');
//Route::delete('/tes/destroy', 'TreavelExpenseController@destroy')->name('tes.destroy');
Route::get('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreate')->name('tes.mydc.create.mycarcreatecurrent');
Route::post('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreateCust')->name('tes.mydc.create.mycarcreatecustom');
Route::post('/tes/mydc/create/car/store', 'TreavelExpenseController@carexpstore')->name('tes.mydc.carexpstore');


Route::get('/tes/admin','AdminTravelExpenseController@index')->name('admin.tes.index');
Route::post('/tes/admin/filter','AdminTravelExpenseController@filter')->name('admin.tes.filter');
Route::post('/tes/admin/filter/docview/', 'AdminTravelExpenseController@showdoc')->name('admin.tes.displayDoc');

Route::resource('/tes','TreavelExpenseController') ;
Route::resource('/cutoffdates','CutoffDatesController');

//cafe routes
Route::resource('/cafe/suppliers','CafeSupplierController') ;
Route::resource('/cafe/families','CafeFamilyController') ;
Route::resource('/cafe/elements','CafeElementController') ;
Route::resource('/cafe/plan','CafePlanController') ;

resources/views/cafe/elements.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container-fluid mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    <h1>Cafeteria Element Management</h1>
  </div>
  @include('layouts.errordiv')
  <div class="container.fluid mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      <thead class="thead-dark">
        <tr>
          <th>{{ __('Element Name') }}</th>
          <th>{{ __('Element Family') }}</th>
          <th>{{ __('Supplier') }}</th>
          <th>{{ __('Description') }}</th>
          <th>{{ __('Monthly limit') }}</th>
          <th>{{ __('Fix amount') }}</th>
          <th>{{ __('Element can be over the limit?') }}</th>
          <th>{{ __('Muliplier') }}</th>
          <th>{{ __('Total Tax') }}</th>
          <th>{{ __('Total Tax - over limit') }}</th>
          <th>{{ __('Yearly limit') }}</th>
          <th>{{ __('Mandatory') }}</th>
          <th>{{ __('Fallback Required') }}</th>
          <th>{{ __('Source to fund') }}</th>
          <th>{{ __('Months allowed') }}</th>
          <th>{{ __('Actions') }}</th>
        </tr>
      </thead>
      <tbody>
        @foreach($elements as $element)
        <tr>
          <td>{{ $element->name }}</td>
          <td>{{ $element->family_id != null ? $element->family->name : '' }}</td>
          <td>{{ $element->supplier->name }}</td>
          <td>{{ $element->description }}</td>
          <td>{{ $element->monthly_limit }}</td>
          <td>{{ $element->fix_amount }}</td>
          <td>{{ $element->limit_breachable }}</td>
          <td>{{ $element->multiplier }}</td>
          <td>{{ $element->tax }} %</td>
          <td>{{ $element->breachtax }} %</td>
          <td>{{ $element->yearly_limit }}</td>
          <td>{{ $element->is_mandatory }}</td>
          <td>{{ $element->needs_fallback }}</td>
          <td>{{ $element->fund_source }}</td>
          <td>{{ $element->allowed_months }}</td>
          <td>
            <a href="{{ route('elements.edit', $element->id) }}">
              <button class="btn btn-primary" type="button" name="editElementButton">
                <span class="glyphicon glyphicon-edit"></span>
              </button>
            </a>
            <form class="" action="{{ route('elements.destroy', $element->id) }}" method="post" style="display:inline;">
              @csrf
              {{ method_field('DELETE') }}
              <button class="btn btn-primary" type="submit" name="disableElementButton">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
      <tfoot class="tfoot-dark">
        <tr>
          <td colspan="16" style="text-align:center;">
            <a href="{{ route('elements.create') }}">
              <button class="btn btn-primary"  type="button" name="addElementBtn">{{ __('Add New Element') }}</button>
            </a>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
@endsection

resources/views/cafe/families.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    <h1>Cafeteria Element Family Management</h1>
  </div>
  @include('layouts.errordiv')
  <div class="container-fluid mc-auto bg-white shadow-sm">
  @foreach($families as $family)
    <table class="table .table-striped .table-hover" style="width:100%">
      <thead class="thead-dark">
        <tr>
          <th colspan="3">{{ __('Name of Family:  '.$family->name) }}</th>
          <th colspan="2"style="text-align:right;">
            <a href="{{ route('families.edit', $family->id) }}">
            <button class="btn btn-primary" type="button" name="editFamilyButton">
              <span class="glyphicon glyphicon-edit"></span>
            </button>
          </a>
          <form class="" action="{{ route('families.destroy', $family->id) }}" method="post" style="display:inline;">
            @csrf
            {{ method_field('DELETE') }}
            <button class="btn btn-primary" type="submit" name="disableFamilyButton">
              <span class="glyphicon glyphicon-trash"></span>
            </button>
          </form>
        </th>
      </tr>
      <tr>
          <th>{{ __('Common Tax: '.$family->common_tax .' %')  }}</th>
          <th>{{ __('Common yearly limit: '.$family->common_limit .' HUF') }}</th>
          <th>{{ __('Family yearly limit: '.$family->overall_limit .' HUF') }}</th>
          <th>{{ __('Mandatory to choose element? '. ($family->mandatory == 1 ? 'Yes':'No')) }}</th>
          <th>{{ __('Number of mandatory items: '.$family->num_of_mandatory ) }}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="5" style="text-align:center;">{{ __('Elements of the family:') }}</td>
      </tr>

      @foreach($family->children as $element)
        <tr>
          <td colspan="3">{{ $element->name }}</td>
          <td>{{ __('Tax: '.$element->tax .' %') }}</td>
          <td>{{ __('Yearly Limit:'.$element->yearly_limit) }}</td>
        </tr>
      @endforeach
    </tbody>
      <tfoot class="tfoot-dark">
        <tr>
          <td colspan="10" style="text-align:center;">

          </td>
        </tr>
      </tfoot>
    </table>
    @endforeach
    <a href="{{ route('families.create') }}">
      <button class="btn btn-primary"  type="button" name="addFamilyBtn">{{ __('Add New Family') }}</button>
    </a>
  </div>
</div>
@endsection

resources/views/cafe/manageelement.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    @if($act == 'new')
      <h1>{{ __('Add New Cafeteria Element') }}</h1>
    @else
      <h1>{{ __('Edit Cafeteria Element') }}</h1>
    @endif
  </div>
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      @if($act == 'new')
      <form class="" action="{{ route('elements.store')}}" method="post">
      @else
      <form class="" action="{{ route('elements.update', $element->id)}}" method="post">
        {{ method_field('PATCH') }}
      @endif
        @csrf
        <tr>
          <td>{{ __('Name:') }}</td>
          <td>
            <input type="text" name="elementName" value="{{ isset($element) ? $element->name : '' }}" placeholder="{{ __('Name of the element') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Element Family:') }}</td>
          <td>
            <select class="" name="elementSelectFamily">
              <option value="0" {{ isset($element) &&  $element->family_id == null ? 'selected': ''}} > {{__('None')}}</option>
              @foreach($fams as $fam)
                <option value="{{ $fam->id }}" {{ isset($element) &&  $element->family_id == $fam->id ? 'selected':''}}> {{ $fam->name }} </option>
              @endforeach
            </select>
          </td>
        </tr>
        <tr>
          <td>{{ __('Supplier:') }}</td>
          <td>
            <select class="" name="elementSelectSupplier">
              @foreach($sups as $sup)
                <option value="{{ $sup->id }}" {{ isset($element) &&  $element->supplier_id == $sup->id ? 'selected':''}}> {{ $sup->name }} </option>
              @endforeach
            </select>
          </td>
        </tr>
        <tr>
          <td>{{ __('Description:') }}</td>
          <td>
            <textarea name="elementDescription" rows="4"  placeholder="{{ __('Description of element: limits, taxes, etc') }}">{{ isset($element) ? $element->description : '' }}</textarea>
          </td>
        </tr>
        <tr>
          <td>{{ __('Monthly limit(Net):') }}</td>
          <td>
            <input type="text" name="elementMLimit" value="{{ isset($element) ? $element->monthly_limit : '' }}" placeholder="{{ __('Monthly limit in HUF') }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Fix amount:(fill only if eleemnt has a fix monthly amount)') }}</td>
          <td>
            <input type="text" name="elementFix" value="{{ isset($element) ? $element->fix_amount : '' }}" placeholder="{{ __('Monthly fix amount in HUF') }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Limit can be breached:') }}</td>
          <td>
            <input type="checkbox" name="elementLimitBrachable" value="1" {{ isset($element) && $element->limit_breachable == 1 ? 'checked' : '' }}>
          </td>
        </tr>
        <tr>
          <td>{{ __('Element Multiplier:') }}</td>
          <td>
            <input type="text" name="elementMultiplier" value="{{ isset($element) ? $element->multiplier : '' }}" placeholder="{{ __('1.0 if taxfree...') }}" />
          </td>
        </tr>
        <tr>
          <td>{{ __('Tax:') }}</td>
          <td>
            <input type="text" name="elementTax" value="{{ isset($element) ? $element->tax : '' }}" placeholder="{{ __('Tax percentage') }}" />
          </td>
        </tr>
        <tr>
          <td>{{ __('Tax - Over limit:') }}</td>
          <td>
            <input type="text" name="elementBreachTax" value="{{ isset($element) ? $element->breachtax : '' }}" placeholder="{{ __('Tax - over limit') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Yearly Limit(Net):') }}</td>
          <td>
            <input type="text" name="elementYLimit" value="{{ isset($element) ? $element->yearly_limit : '' }}" placeholder="{{ __('Yearly limit in HUF') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Manadatory:') }}</td>
          <td>
            <input type="checkbox" name="elementMandatory" value="1" {{ isset($element) && $element->is_mandatory == 1 ? 'checked' : '' }}>
          </td>
        </tr>
        <tr>
          <td>{{ __('Element needs fallback:') }}</td>
          <td>
            <input type="checkbox" name="elementNeedsFallback" value="1" {{ isset($element) && $element->needs_fallback == 1 ? 'checked' : '' }}>
          </td>
        </tr>
        <tr>
          <td>{{ __('Element Funded from:') }}</td>
          <td>
            <select class="" name="selectElementFund">
              <option value="cafe" {{ isset($element) && $element->fund_source == 'cafe' ? 'selected' : ''  }}>{{ __('Cafeteria Allowance') }}</option>
              <option value="salary" {{ isset($element) && $element->fund_source == 'salary' ? 'selected' : ''  }}>{{ __('Salary') }}</option>
            </select>
          </td>
        </tr>
        <tr>
          <td colspan="2">{{ __('Months the element can be requested:') }}</td>
        </tr>
        <tr>
          <td colspan="2">
            <table>
              <tr>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('all',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }} {{ !(isset($element)) ? 'highlightedMonth':'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthAll" value="all" {{ isset($element) && (stripos('all',$element->allowed_months) !== false) ? 'checked' :'' }}
                  {{ !(isset($element)) ? 'checked':'' }}/>
                  {{ __('All') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('jan',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthJan" value="jan" {{ isset($element) && (stripos('jan',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Jan') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('feb',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthFeb" value="feb" {{ isset($element) && (stripos('feb',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Feb') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('mar',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthMar" value="mar" {{ isset($element) && (stripos('mar',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Mar') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('apr',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthApr" value="apr" {{ isset($element) && (stripos('apr',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Apr') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('may',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthMay" value="may" {{ isset($element) && (stripos('may',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('May') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('jun',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthJun" value="jun" {{ isset($element) && (stripos('jun',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Jun') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('jul',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthJul" value="jul" {{ isset($element) && (stripos('jul',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Jul') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('aug',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthAug" value="aug" {{ isset($element) && (stripos('aug',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Aug') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('sep',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthSep" value="sep" {{ isset($element) && (stripos('sep',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Sep') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('oct',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthOct" value="oct" {{ isset($element) && (stripos('oct',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Oct') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('nov',$element->allowed_months) !== false) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthNov" value="nov" {{ isset($element) && (stripos('nov',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Nov') }}
                </td>
                <td class="cafeAllowedMonthTD {{ isset($element) && (stripos('dec',$element->allowed_months) !== false ) ? 'highlightedMonth' :'' }}">
                  <input class="cafeAllowedMonthCB hidden" type="checkbox" name="elemAllowedMonthDec" value="dec" {{ isset($element) && (stripos('dec',$element->allowed_months) !== false) ? 'checked' :'' }}>
                  {{ __('Dec') }}
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <button class="btn btn-primary" type="submit" name="saveElement">Save</button>
            <button class="btn btn-primary" type="button" onclick="window.location='{{ URL::previous() }}'" name="cancelManageElement">Cancel</button>
          </td>
        </tr>
      </form>
    </table>
  </div>
</div>
@endsection

resources/views/cafe/managefamilies.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    @if($act == 'new')
      <h1>{{ __('Add New Cafeteria Element') }}</h1>
    @else
      <h1>{{ __('Edit Cafeteria Element') }}</h1>
    @endif
  </div>
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      @if($act == 'new')
      <form class="" action="{{ route('families.store')}}" method="post">
      @else
      <form class="" action="{{ route('families.update', $family->id)}}" method="post">
        {{ method_field('PATCH') }}
      @endif
        @csrf
        <tr>
          <td>{{ __('Family Name')}}</td>
          <td>
            <input type="text" name="familyName" value="{{ isset($family) ? $family->name : '' }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Common Tax')}}</td>
          <td>
            <input type="text" name="familyCommonTax" value="{{ isset($family) ? $family->common_tax : '' }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Common Limit')}}</td>
          <td>
            <input type="text" name="familyCommonLimit" value="{{ isset($family) ? $family->common_limit : '' }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Overall Limit')}}</td>
          <td>
            <input type="text" name="familyOverallLimit" value="{{ isset($family) ? $family->overall_limit : '' }}"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Has manadtory element?')}}</td>
          <td>
            <input type="checkbox" name="familyMandatory" value="1"/>
          </td>
        </tr>
        <tr>
          <td>{{ __('Number of mandatory elements')}}</td>
          <td>
            <input type="number" name="familyMandatoryNum" value="{{ isset($family) ? $family->num_of_mandatory : '' }}"/>
          </td>
        </tr>
        <tr>
          <td colspan="2"style="text-align:center;">{{ __('Elements in Family:')}}</td>
        </tr>
        @if(isset($elements))
          @foreach($elements as $el)
            <tr>
              <td colspan="2" style="background:#dcf2e2;text-align:center;">
                @if(isset($family))
                <input type="checkbox" name="addElement_{{ $el->id }}" value="{{ $el->id }}"
                {{ isset($family) && $el->family_id == $family->id ? 'checked ' : ''  }}
                {{ isset($family) && ($el->family_id != $family->id && $el->family_id != null) ? 'disabled ' : '' }}/>
                @else
                <input type="checkbox" name="addElement_{{ $el->id }}" value="{{ $el->id }}" {{ $el->family_id != null ? 'disabled ' : '' }}/>
                @endif
                {{ $el->name }}
              </td>
            </tr>
          @endforeach
        @endif
        <tr>
          <td colspan="2">
            <button class="btn btn-primary" type="submit" name="saveFamily">Save</button>
            <button class="btn btn-primary" type="button" onclick="window.location='{{ URL::previous() }}'" name="cancelManageFamily">Cancel</button>
          </td>
        </tr>
      </form>
    </table>
  </div>
@endsection

resources/views/cafe/managesupplier.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    @if($act == 'new')
      <h1>{{ __('Add New Supplier') }}</h1>
    @else
      <h1>{{ __('Edit Supplier') }}</h1>
    @endif
  </div>
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      @if($act == 'new')
      <form class="" action="{{ route('suppliers.store')}}" method="post">
      @else
      <form class="" action="{{ route('suppliers.update', $sup->id)}}" method="post">
        {{ method_field('PATCH') }}
      @endif
        @csrf
        <tr>
          <td>{{ __('Name:') }}</td>
          <td>
            <input type="text" name="supplierName" value="{{ isset($sup) ? $sup->name : '' }}" placeholder="{{ __('Name of the supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Address:') }}</td>
          <td>
            <input type="text" name="supplierAddress" value="{{ isset($sup) ? $sup->address : '' }}" placeholder="{{ __('Address of supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('E-mail:') }}</td>
          <td>
            <input type="text" name="supplierMail" value="{{ isset($sup) ? $sup->mail : '' }}" placeholder="{{ __('E-mail of supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Phone:') }}</td>
          <td>
            <input type="text" name="supplierPhone" value="{{ isset($sup) ? $sup->phone : '' }}" placeholder="{{ __('Phone number of supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Contact Person:') }}</td>
          <td>
            <input type="text" name="supplierContact" value="{{ isset($sup) ? $sup->contact_person : '' }}" placeholder="{{ __('Contact Person within the supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Account:') }}</td>
          <td>
            <input type="text" name="supplierAccount" value="{{ isset($sup) ? $sup->account : '' }}" placeholder="{{ __('Financial account of supplier') }}">
          </td>
        </tr>
        <tr>
          <td>{{ __('Comments:') }}</td>
          <td>
            <textarea name="supplierComment" rows="3"  placeholder="{{ __('Any commnets about the supplier') }}">{{ isset($sup) ? $sup->comment : '' }}</textarea>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <button class="btn btn-primary" type="submit" name="saveSupplier">Save</button>
            <button class="btn btn-primary" type="button" name="cancelManageSupplier">Cancel</button>
          </td>
        </tr>
      </form>
    </table>
  </div>
</div>
@endsection

resources/views/cafe/suppliers.blade.php
@extends('layouts.homeLayout')
@section('content')
<div class="container mc-auto bg-white shadow-sm">
  <div class="container mc-auto bg-white shadow-sm">
    <h1>Supplier Management</h1>
  </div>
  @include('layouts.errordiv')
  <div class="container mc-auto bg-white shadow-sm">
    <table class="table .table-striped .table-hover" style="width:100%">
      <thead class="thead-dark">
        <tr>
          <th>{{ __('Name') }}</th>
          <th>{{ __('Address') }}</th>
          <th>{{ __('E-mail') }}</th>
          <th>{{ __('Phone') }}</th>
          <th>{{ __('Contact Person') }}</th>
          <th>{{ __('Account') }}</th>
          <th>{{ __('Comments') }}</th>
          <th>{{ __('Actions') }}</th>
        </tr>
      </thead>
      <tbody>
        @foreach($suppliers as $sup)
        <tr>
          <td>{{ $sup->name }}</td>
          <td>{{ $sup->address }}</td>
          <td>{{ $sup->mail }}</td>
          <td>{{ $sup->phone }}</td>
          <td>{{ $sup->contact_person }}</td>
          <td>{{ $sup->account }}</td>
          <td>{{ $sup->comment }}</td>
          <td>
            <a href="{{ route('suppliers.edit', $sup->id) }}">
              <button class="btn btn-primary"   type="button" name="editSupplierButton">
                <span class="glyphicon glyphicon-edit"></span>
              </button>
            </a>
            <form class="" action="{{ route('suppliers.destroy', $sup->id) }}" method="post" style="display:inline;">
              @csrf
              {{ method_field('DELETE') }}
              <button class="btn btn-primary"   type="submit" name="DisableSupplierButton">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
      <tfoot class="tfoot-dark">
        <tr>
          <td colspan="8" style="text-align:center;">
            <a href="{{ route('suppliers.create') }}">
              <button class="btn btn-primary"  type="button" name="addSupplierBtn">{{ __('Add New Supplier') }}</button>
            </a>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
@endsection