routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
})->name('login');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cafe', 'HomeController@cafe')->name('cafe');


Route::resource('/userman','UserController');
Route::post('/userman/search','UserController@search')->name('userman.search');

Route::get('/myprofile','MyProfileController@index')->name('myprofile');
Route::get('/myprofile/edit','MyProfileController@edit')->name('myprofile.edit');
Route::patch('/myprofile/update','MyProfileController@update')->name('myprofile.update');

Route::get('/tes/myht', 'TreavelExpenseController@myht')->name('tes.myht');
Route::get('/tes/mydc', 'TreavelExpenseController@mydc')->name('tes.mydc');
Route::get('/tes/myht/create', 'TreavelExpenseController@create')->name('tes.myht.create');
Route::get('/tes/mydc/create', 'TreavelExpenseController@create')->name('tes.mydc.create');
//Route::post('/tes/store', 'TreavelExpenseController@store')->name('tes.store');
//Route::delete('/tes/destroy', 'TreavelExpenseController@destroy')->name('tes.destroy');
Route::get('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreate')->name('tes.mydc.create.mycarcreatecurrent');
Route::post('/tes/mydc/create/car', 'TreavelExpenseController@mycarCreateCust')->name('tes.mydc.create.mycarcreatecustom');
Route::post('/tes/mydc/create/car/store', 'TreavelExpenseController@carexpstore')->name('tes.mydc.carexpstore');


Route::get('/tes/admin','AdminTravelExpenseController@index')->name('admin.tes.index');
Route::post('/tes/admin/filter','AdminTravelExpenseController@filter')->name('admin.tes.filter');
Route::post('/tes/admin/filter/docview/', 'AdminTravelExpenseController@showdoc')->name('admin.tes.displayDoc');

Route::resource('/tes','TreavelExpenseController') ;
Route::resource('/cutoffdates','CutoffDatesController');

//cafe routes
Route::resource('/cafe/suppliers','CafeSupplierController') ;
Route::resource('/cafe/families','CafeFamilyController') ;
Route::resource('/cafe/elements','CafeElementController') ;
Route::resource('/cafe/plan','CafePlanController') ;

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/docmodal.blade.php
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Approve/Reject Expense</h4>
      </div>
      <div class="modal-body">
        <form class="" action="index.html" method="post">
          @csrf
          <button type="button" name="button">Approve</button>
          <button type="button" name="button">Reject</button>
          <input type="textbox" name="rejReason" value="" placeholder="Reason of rejection">
        </form>
        <div class="docDisplay">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

resources/views/layouts/errordiv.blade.php
<div class="error ">
  @if ($errors->any())
  <div class="alert alert-danger container mc-auto shadow-sm">
      <ul>
          @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
          @endforeach
      </ul>
  </div>
  @endif
</div>

resources/views/layouts/homeLayout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Horus') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>

      <script src="{{ asset('js/custom.js') }}" ></script>



    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>
                    <!-- center Side Of Navbar -->
                    <ul class="navbar-nav mc-auto">
                      <li class="nav-item dropdown">
                        <a  class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Admin <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ route('userman.create' ) }}">
                              {{ __('Add New User') }}
                          </a>
                            <a class="dropdown-item" href="{{ route('userman.index') }}">
                                {{ __('Search/Edit Users') }}
                            </a>
                        </div>
                      </li>
                      <li class="nav-item dropdown">
                        <a  class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Cafeteria <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('plan.index') }}">
                                {{ __('Cafeteri Declaration') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('elements.index') }}">
                                {{ __('Cafeteria elements') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('families.index') }}">
                                {{ __('Element Families') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('suppliers.index') }}">
                                {{ __('Suppliers') }}
                            </a>
                        </div>
                      </li>

                      <li class="nav-item dropdown">
                        <a  class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Travel Expense <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('tes.myht') }}">
                                {{ __('Home Travel') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('tes.mydc') }}">
                                {{ __('Daily Commute') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('admin.tes.index') }}">
                                {{ __('Report') }}
                            </a>
                            <a class="dropdown-item" href="/cutoffdates">
                                {{ __('Cutoff Date Management') }}
                            </a>
                        </div>
                      </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->username }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('myprofile' ) }}">
                                        {{ __('My Profile') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>

                                </div>
                            </li>



                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

</body>
</html>